In [9]:
# Import LUSID
import lusid
import lusidtools.cocoon.cocoon as cocoon_tools
import lusid_sample_data as sd
from lusidjam import RefreshingToken
import pandas as pd
import numpy as np
import os
import pytz
import printer as prettyprint
from datetime import datetime
import pylab
import matplotlib.pyplot as plt

# Authenticate our user and create our API client
secrets_path = '/Users/msingh/Projects/lusidws/secrets.json'

api_factory = lusid.utilities.ApiClientFactory(
    token=RefreshingToken(),
    api_secrets_filename = secrets_path,
    app_name="LusidJupyterNotebook")

In [6]:
%matplotlib inline
%pylab inline

# Set style to fivethirtyeight to create clean and clear looking graphs
plt.style.use('fivethirtyeight')

# Define a dictionary containing default plotting configurations
params = {
    'legend.fontsize': 'small',
    'figure.figsize': (15, 10),
    'axes.labelsize': 'small',
    'axes.titlesize':'medium',
    'xtick.labelsize':'small',
    'ytick.labelsize':'small'
}

pylab.rcParams.update(params)

Populating the interactive namespace from numpy and matplotlib

## import and create instruments

In [7]:
uk_instrument_master = pd.read_csv('data/global-fund-UK-instrument-master.csv')
uk_instrument_master.head(n=20)

,instrument_name,client_internal,currency,isin,figi,exchange_code,country_issue,ticker,market_sector,security_type,coupon,s&p rating
0,BP_LondonStockEx_BP,imd_43535553,GBP,GB0007980591,BBG000C05BD1,LN,united_kingdom,BP/,equity,common_stock,NaN,NaN
1,BurfordCapital_LondonStockEx_BUR,imd_43534356,GBP,GG00B4L84979,BBG000PN88Q7,LN,united_kingdom,BUR,equity,common_stock,NaN,NaN
2,EKFDiagnostics_LondonStockEx_EKF,imd_34535355,GBP,GB0031509804,BBG000BVNBN3,LN,united_kingdom,EKF,equity,common_stock,NaN,NaN
3,Glencore_LondonStockEx_GLEN,imd_34534555,GBP,JE00B4T3BW64,BBG001MM1KV4,LN,united_kingdom,GLEN,equity,common_stock,NaN,NaN
4,JustEat_LondonStockEx_JE,imd_35436366,GBP,GB00BKX5CN86,BBG0065YWM39,LN,united_kingdom,JE/,equity,common_stock,NaN,NaN
5,Kingfisher_LondonStockEx_KGF,imd_34535552,GBP,GB0033195214,BBG000BKH1W6,LN,united_kingdom,KGF,equity,common_stock,NaN,NaN
6,MicroFocus_LondonStockEx_MCRO,imd_34567338,GBP,GB00BD8YWM01,BBG000G4KKD2,LN,united_kingdom,MCRO,equity,common_stock,NaN,NaN
7,RELXGroup_LondonStockEx_REL,imd_43532542,GBP,GB00B2B0DG97,BBG000D03XD4,LN,united_kingdom,REL,equity,common_stock,NaN,NaN
8,Sage_LondonStockEx_SGE,imd_23536673,GBP,GB00B8C3BL03,BBG000BN0PP3,LN,united_kingdom,SGE,equity,common_stock,NaN,NaN
9,TESCO_LondonStockEx_TSCO,imd_34634673,GBP,GB0008847096,BBG000BF46Y8,LN,united_kingdom,TSCO,equity,common_stock,NaN,NaN
10,UKGiltTreasury_2.0_2025,imd_34534536,GBP,GB00BTHH2R79,BBG0088JSC32,LN,united_kingdom,UKT 2 09/07/25,govt,uk_gilt_stock,2.00,AA
11,UKGiltTreasury_3.5_2045,imd_54234532,GBP,GB00BN65R313,BBG006N6HZM7,LN,united_kingdom,UKT 3.5 01/22/45,govt,uk_gilt_stock,3.50,AA
12,UKGiltTreasury_3.75_2021,imd_34643653,GBP,GB00B4RMG977,BBG001KKJLR4,LN,united_kingdom,UKT 3.75 09/07/21,govt,uk_gilt_stock,3.75,AA
13,UKGiltTreasury_4.5_2034,imd_34534534,GBP,GB00B52WS153,BBG0000D14P3,LN,united_kingdom,UKT 4.5 09/07/34,govt,uk_gilt_stock,4.50,AA
14,WPP_LondonStockEx_WPP,imd_34536734,GBP,JE00B8KF9B49,BBG000BF6B57,LN,united_kingdom,WPP,equity,common_stock,NaN,NaN
15,Whitebread_LondonStockEx_WTB,imd_35349900,GBP,GB00B1KJJ408,BBG000BRVH05,LN,united_kingdom,WTB,equity,common_stock,NaN,NaN
16,TESCO_6.13_2022,imd_34001121,GBP,XS0414345974,NaN,NaN,united_kingdom,NaN,corporate,corporate_bond,6.13,A-

In [8]:
instrument_properties_scope = 'InstrumentProperties005'

instrument_identifier_mapping = {
    "Figi": "figi",
    "Isin": "isin",
    "ClientInternal": "client_internal",
    "Ticker": "ticker"
}

instrument_mapping_required = {
    "name": "instrument_name"
}

instrument_mapping_optional = {}

responses = cocoon_tools.load_from_data_frame(
    api_factory=api_factory, 
    scope=instrument_properties_scope, 
    data_frame=uk_instrument_master, 
    mapping_required=instrument_mapping_required, 
    mapping_optional=instrument_mapping_optional, 
    file_type="instrument", 
    identifier_mapping=instrument_identifier_mapping, 
    property_columns=[
        "exchange_code", 
        "country_issue", 
        "market_sector",
        "security_type",
        "coupon",
        "s&p rating",
        "currency"])

NameError: name 'prettyprint' is not defined

In [11]:
prettyprint.instrument_response(responses["instruments"]["success"][0])

Instruments Successfully Upserted:

                      Instrument ClientInternal ID LUSID Instrument ID
0   ClientInternal: imd_34535355      imd_34535355       LUID_00003D6D
1   ClientInternal: imd_43534356      imd_43534356       LUID_00003D6E
2   ClientInternal: imd_34001121      imd_34001121       LUID_00003D6F
3   ClientInternal: imd_35436366      imd_35436366       LUID_00003D6G
4   ClientInternal: imd_43532542      imd_43532542       LUID_00003D6H
5   ClientInternal: imd_34534555      imd_34534555       LUID_00003D6I
6   ClientInternal: imd_34534536      imd_34534536       LUID_00003D6J
7   ClientInternal: imd_34535552      imd_34535552       LUID_00003D6K
8   ClientInternal: imd_23536673      imd_23536673       LUID_00003D6L
9   ClientInternal: imd_34534534      imd_34534534       LUID_00003D6M
10  ClientInternal: imd_34567338      imd_34567338       LUID_00003D6N
11  ClientInternal: imd_35349900      imd_35349900       LUID_00003D6O
12  ClientInternal: imd_34643653      imd_34643653       LUID_00003D6P
13  ClientInternal: imd_54234532      imd_54234532       LUID_00003D6Q
14  ClientInternal: imd_34634673      imd_34634673       LUID_00003D6R
15  ClientInternal: imd_43535553      imd_43535553       LUID_00003D6S
16  ClientInternal: imd_34536734      imd_34536734       LUID_00003D6T

## Create a Portfolio with "FirstInFirstOut" (FIFO) Accounting Method

In [13]:
portfolio_code = "UK12XC2"

portfolio = pd.DataFrame([
    {
        "code": portfolio_code,
        "display_name": "UK Equity Fund",
        "description": "UK Growth Fund Trading in UK Tradeable Equities",
        "base_currency": "GBP",
        "accounting_method": "FirstInFirstOut",
        "created": datetime(year=2010, day=1, month=1, tzinfo=pytz.UTC)
    }
])

portfolio.head()

,code,display_name,description,base_currency,accounting_method,created
0,UK12XC2,UK Equity Fund,UK Growth Fund Trading in UK Tradeable Equities,GBP,FirstInFirstOut,2010-01-01 00:00:00+00:00

In [14]:
trading_scope = "AccountingDemoScope"

portfolio_mapping_required = {
    "code": "code",
    "display_name": "display_name",
    "base_currency": "base_currency",
    "accounting_method": "accounting_method"
}

portfolio_mapping_optional = {
    "description": "description",
    "created": "created"
}

responses = cocoon_tools.load_from_data_frame(
    api_factory=api_factory, 
    scope=trading_scope, 
    data_frame=portfolio, 
    mapping_required=portfolio_mapping_required, 
    mapping_optional=portfolio_mapping_optional, 
    file_type="portfolio")

prettyprint.portfolio_response(responses["portfolios"]["success"][0])

Portfolio Created
Scope: AccountingDemoScope
Code: UK12XC2
Portfolio Effective From: 2010-01-01 00:00:00+00:00
Portfolio Created On: 2021-12-28 10:04:12.776928+00:00